/*
* You are given two strings s and t.
* String t is generated by random shuffling string s and then add one more letter at a random position.
* Return the letter that was added to t.
*/

class Solution {
public:
    char findTheDifference(string s, string t) {
        if( t.length() == 1)
        {
            return t[0];
        }

        string compare = t;

        for(int i = 0; i < s.length(); i++)
        {
            compare.erase(compare.find(s[i]), 1);
        }

        return compare[0];
    }
};
